In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
# Load dataset
df = pd.read_csv("autism.csv")

# Preview
df.head()

   rownames  childid sicdegp  age2  vsae gender   race bestest2
0         1        1    high     0     6   male  white      pdd
1         2        1    high     1     7   male  white      pdd
2         3        1    high     3    18   male  white      pdd
3         4        1    high     7    25   male  white      pdd
4         5        1    high    11    27   male  white      pdd

In [4]:
# Check missing values
print(df.isnull().sum())



df.head()

rownames    0
childid     0
sicdegp     0
age2        0
vsae        0
gender      0
race        0
bestest2    0
dtype: int64

   rownames  childid  sicdegp  age2  vsae  gender  race  bestest2
0         1        1        0     0     6       1     1         1
1         2        1        0     1     7       1     1         1
2         3        1        0     3    18       1     1         1
3         4        1        0     7    25       1     1         1
4         5        1        0    11    27       1     1         1

In [5]:
cat_cols = df.select_dtypes(include=['object', 'string']).columns

for col in cat_cols:
    df[col] = LabelEncoder().fit_transform(df[col].astype(str))

In [7]:
df.columns.tolist()

['rownames',
 'childid',
 'sicdegp',
 'age2',
 'vsae',
 'gender',
 'race',
 'bestest2']

In [10]:
print(df.head())
print(df.columns)

   rownames  childid  sicdegp  age2  vsae  gender  race  bestest2
0         1        1        0     0     6       1     1         1
1         2        1        0     1     7       1     1         1
2         3        1        0     3    18       1     1         1
3         4        1        0     7    25       1     1         1
4         5        1        0    11    27       1     1         1
Index(['rownames', 'childid', 'sicdegp', 'age2', 'vsae', 'gender', 'race',
       'bestest2'],
      dtype='str')

In [14]:
for col in df.columns:
    print(f"'{col}'")

'rownames'
'childid'
'sicdegp'
'age2'
'vsae'
'gender'
'race'
'bestest2'

In [16]:
print(dir())

['ExtraTreesClassifier', 'In', 'LabelEncoder', 'Out', 'RandomForestClassifier', '_', '_2', '_3', '_4', '_7', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__session__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'accuracy_score', 'cat_cols', 'classification_report', 'col', 'confusion_matrix', 'df', 'et_model', 'exit', 'get_ipython', 'label_encoders', 'le', 'np', 'open', 'pd', 'quit', 'rf_model', 'target_column', 'train_test_split']

In [24]:
df.head()
df.columns

Index(['rownames', 'childid', 'sicdegp', 'age2', 'vsae', 'gender', 'race',
       'bestest2'],
      dtype='str')

In [28]:
print(df.columns)

Index(['rownames', 'childid', 'sicdegp', 'age2', 'vsae', 'gender', 'race',
       'bestest2'],
      dtype='str')