In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Merge2.csv")

# View dataset
print(df.head())
print(df.info())

         date      a   b    c
0  2022-03-01  12000  50   60
1  2022-03-02  27000  90  990
2  2022-03-03  19000  17  750
3  2022-03-04  70000  60  900
4  2022-03-05   6000   7  810
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    31 non-null     str
 1   a       31 non-null     int64
 2   b       31 non-null     int64
 3   c       31 non-null     int64
dtypes: int64(3), str(1)
memory usage: 1.4 KB
None

In [7]:
df.select_dtypes(include=['object', 'string', 'category'])

          date
0   2022-03-01
1   2022-03-02
2   2022-03-03
3   2022-03-04
4   2022-03-05
5   2022-03-06
6   2022-03-07
7   2022-03-08
8   2022-03-09
9   2022-03-10
10  2022-03-11
11  2022-03-12
12  2022-03-13
13  2022-03-14
14  2022-03-15
15  2022-03-16
16  2022-03-17
17  2022-03-18
18  2022-03-19
19  2022-03-20
20  2022-03-21
21  2022-03-22
22  2022-03-23
23  2022-03-24
24  2022-03-25
25  2022-03-26
26  2022-03-27
27  2022-03-28
28  2022-03-29
29  2022-03-30
30  2022-03-31

In [8]:
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [10]:
df.head()
df.index

RangeIndex(start=0, stop=31, step=1)

In [11]:
df = df.reset_index()

In [13]:
df.head()

   index  date        a     b      c
0      0     0  12000.0  50.0   60.0
1      1     1  27000.0  90.0  990.0
2      2     2  19000.0  17.0  750.0
3      3     3  70000.0  60.0  900.0
4      4     4   6000.0   7.0  810.0

In [15]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'SimpleImputer', 'RandomForestClassifier', 'ExtraTreesClassifier', 'DecisionTreeClassifier', 'accuracy_score', 'classification_report', 'confusion_matrix', '_i2', 'df', '_i3', 'numeric_cols', 'categorical_cols', 'num_imputer', 'cat_imputer', '_i4', '_i5', '_5', '_i6', '_6', '_i7', '_7', '_i8', 'label_encoders', 'col', 'le', '_i9', '_i10', '_10', '_i11', '_i12', '_i13', '_13', '_i14', 'rf_model', '_i15'])

In [23]:
print(df.columns)

Index(['index', 'date', 'a', 'b', 'c'], dtype='str')

In [24]:
df.head()

   index  date        a     b      c
0      0     0  12000.0  50.0   60.0
1      1     1  27000.0  90.0  990.0
2      2     2  19000.0  17.0  750.0
3      3     3  70000.0  60.0  900.0
4      4     4   6000.0   7.0  810.0

In [25]:
for col in df.columns:
    print(col)

index
date
a
b
c

In [31]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load data
data = load_iris()
X = data.data
y = data.target

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Predict
dt_pred = dt_model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, dt_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [33]:
print(dir())

['DecisionTreeClassifier', 'ExtraTreesClassifier', 'In', 'LabelEncoder', 'Out', 'RandomForestClassifier', 'SimpleImputer', 'X', 'X_test', 'X_train', '_', '_10', '_13', '_24', '_5', '_6', '_7', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__session__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i19', '_i2', '_i20', '_i21', '_i22', '_i23', '_i24', '_i25', '_i26', '_i27', '_i28', '_i29', '_i3', '_i30', '_i31', '_i32', '_i33', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'accuracy', 'accuracy_score', 'cat_imputer', 'categorical_cols', 'classification_report', 'col', 'confusion_matrix', 'data', 'df', 'dt_model', 'dt_pred', 'et_model', 'exit', 'get_ipython', 'label_encoders', 'le', 'load_iris', 'np', 'num_imputer', 'numeric_cols', 'open', 'pd', 'quit', 'rf_model', 'train_test_split', 'y', 'y_test', 'y_train']

In [36]:
print(dir())

['DecisionTreeClassifier', 'ExtraTreesClassifier', 'In', 'LabelEncoder', 'Out', 'RandomForestClassifier', 'SimpleImputer', 'X', 'X_test', 'X_train', '_', '_10', '_13', '_24', '_5', '_6', '_7', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__session__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i19', '_i2', '_i20', '_i21', '_i22', '_i23', '_i24', '_i25', '_i26', '_i27', '_i28', '_i29', '_i3', '_i30', '_i31', '_i32', '_i33', '_i34', '_i35', '_i36', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'accuracy', 'accuracy_score', 'cat_imputer', 'categorical_cols', 'classification_report', 'col', 'confusion_matrix', 'data', 'df', 'dt_model', 'dt_pred', 'et_model', 'exit', 'get_ipython', 'label_encoders', 'le', 'load_iris', 'np', 'num_imputer', 'numeric_cols', 'open', 'pd', 'quit', 'rf_model', 'train_test_split', 'y', 'y_test', 'y_train']

In [37]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import pandas as pd\nimport numpy as np\n\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom sklearn.impute import SimpleImputer\n\nfrom sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier\nfrom sklearn.tree import DecisionTreeClassifier\n\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix',
  'df = pd.read_csv("Merge2.csv")\n\n# View dataset\nprint(df.head())\nprint(df.info())',
  '# Check missing values\nprint(df.isnull().sum())\n\n# Separate numeric and categorical columns\nnumeric_cols = df.select_dtypes(include=np.number).columns\ncategorical_cols = df.select_dtypes(include=\'object\').columns\n\n# Fill missing values\nnum_imputer = SimpleImputer(strategy="mean")\ndf[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])\n\ncat_imputer = SimpleImputer(strategy="most_frequent")\ndf[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])',
  "categorical_cols = df.select_dtypes(include='object').columns",
  "df.select_dtypes(include='object')",
  "df.select_dtypes(include='object')",
  "df.select_dtypes(include=['object', 'string', 'category'])",
  'label_encoders = {}\n\nfor col in categorical_cols:\n    le = LabelEncoder()\n    df[col] = le.fit_transform(df[col])\n    label_encoders[col] = le',
  'X = df.drop("target", axis=1)\ny = df["target"]',
  'df.head()\ndf.index',
  'df = df.reset_index()',
  'X_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)',
  'df.head()',
  'rf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\nrf_model.fit(X_train, y_train)\n\nrf_pred = rf_model.predict(X_test)',
  'print(globals().keys())',
  'et_model = ExtraTreesClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\net_model.fit(X_train, y_train)\n\net_pred = et_model.predict(X_test)',
  'import pandas as pd\n\nimportances = pd.Series(et_model.feature_importances_, index=X_train.columns)\nprint(importances.sort_values(ascending=False).head(10))',
  'from sklearn.ensemble import ExtraTreesClassifier\n\net_model = ExtraTreesClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\net_model.fit(X_train, y_train)   # MUST run first\n\nimport pandas as pd\n\nimportances = pd.Series(et_model.feature_importances_, index=X_train.columns)\nprint(importances.sort_values(ascending=False).head(10))',
  'print(et_model)\nprint(len(et_model.estimators_))',
  'X_train.isnull().sum().sum()',
  'print(type(X_train))\nprint(X_train.shape)',
  'import pandas as pd\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import ExtraTreesClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\n# ----------------------------\n# 1. Define features & target\n# ----------------------------\nX = df.drop("target", axis=1)   # change "target" to your label column\ny = df["target"]\n\n# ----------------------------\n# 2. Train/test split\n# ----------------------------\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y,\n    test_size=0.2,\n    random_state=42\n)\n\n# ----------------------------\n# 3. Train model\n# ----------------------------\net_model = ExtraTreesClassifier(\n    n_estimators=100,\n    random_state=42,\n    n_jobs=-1\n)\n\net_model.fit(X_train, y_train)\n\n# ----------------------------\n# 4. Predictions\n# ----------------------------\net_pred = et_model.predict(X_test)\n\n# ----------------------------\n# 5. Evaluation\n# ----------------------------\nprint("Accuracy:", accuracy_score(y_test, et_pred))\nprint("\\nClassification Report:\\n", classification_report(y_test, et_pred))\n\n# ----------------------------\n# 6. Feature Importance\n# ----------------------------\nimportances = pd.Series(et_model.feature_importances_, index=X.columns)\nprint("\\nTop 10 Features:\\n")\nprint(importances.sort_values(ascending=False).head(10))',
  'print(df.columns)',
  'df.head()',
  'for col in df.columns:\n    print(col)',
  'dt_model = DecisionTreeClassifier(random_state=42)\ndt_model.fit(X_train, y_train)\n\ndt_pred = dt_model.predict(X_test)',
  'print(X.shape, y.shape)',
  'from sklearn.metrics import accuracy_score\n\naccuracy = accuracy_score(y_test, dt_pred)\nprint("Accuracy:", accuracy)',
  'from sklearn.metrics import accuracy_score\n\naccuracy = accuracy_score(y_test, dt_pred)\nprint("Accuracy:", accuracy)',
  'print(X.shape)\nprint(y.shape)',
  'from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.metrics import accuracy_score\n\n# Load data\ndata = load_iris()\nX = data.data\ny = data.target\n\n# Split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Train model\ndt_model = DecisionTreeClassifier(random_state=42)\ndt_model.fit(X_train, y_train)\n\n# Predict\ndt_pred = dt_model.predict(X_test)\n\n# Evaluate\naccuracy = accuracy_score(y_test, dt_pred)\nprint("Accuracy:", accuracy)',
  'print("Extra Trees Accuracy:", accuracy_score(y_test, et_pred))\nprint(classification_report(y_test, et_pred))',
  'print(dir())',
  'predict(',
  'print("Random Forest Confusion Matrix")\nprint(confusion_matrix(y_test, rf_pred))',
  'print(dir())',
  'locals()'],
 '_oh': {5:           date
  0   2022-03-01
  1   2022-03-02
  2   2022-03-03
  3   2022-03-04
  4   2022-03-05
  5   2022-03-06
  6   2022-03-07
  7   2022-03-08
  8   2022-03-09
  9   2022-03-10
  10  2022-03-11
  11  2022-03-12
  12  2022-03-13
  13  2022-03-14
  14  2022-03-15
  15  2022-03-16
  16  2022-03-17
  17  2022-03-18
  18  2022-03-19
  19  2022-03-20
  20  2022-03-21
  21  2022-03-22
  22  2022-03-23
  23  2022-03-24
  24  2022-03-25
  25  2022-03-26
  26  2022-03-27
  27  2022-03-28
  28  2022-03-29
  29  2022-03-30
  30  2022-03-31,
  6:           date
  0   2022-03-01
  1   2022-03-02
  2   2022-03-03
  3   2022-03-04
  4   2022-03-05
  5   2022-03-06
  6   2022-03-07
  7   2022-03-08
  8   2022-03-09
  9   2022-03-10
  10  2022-03-11
  11  2022-03-12
  12  2022-03-13
  13  2022-03-14
  14  2022-03-15
  15  2022-03-16
  16  2022-03-17
  17  2022-03-18
  18  2022-03-19
  19  2022-03-20
  20  2022-03-21
  21  2022-03-22
  22  2022-03-23
  23  2022-03-24
  24  2022-03-25
  25  2022-03-26
  26  2022-03-27
  27  2022-03-28
  28  2022-03-29
  29  2022-03-30
  30  2022-03-31,
  7:           date
  0   2022-03-01
  1   2022-03-02
  2   2022-03-03
  3   2022-03-04
  4   2022-03-05
  5   2022-03-06
  6   2022-03-07
  7   2022-03-08
  8   2022-03-09
  9   2022-03-10
  10  2022-03-11
  11  2022-03-12
  12  2022-03-13
  13  2022-03-14
  14  2022-03-15
  15  2022-03-16
  16  2022-03-17
  17  2022-03-18
  18  2022-03-19
  19  2022-03-20
  20  2022-03-21
  21  2022-03-22
  22  2022-03-23
  23  2022-03-24
  24  2022-03-25
  25  2022-03-26
  26  2022-03-27
  27  2022-03-28
  28  2022-03-29
  29  2022-03-30
  30  2022-03-31,
  10: RangeIndex(start=0, stop=31, step=1),
  13:    index  date        a     b      c
  0      0     0  12000.0  50.0   60.0
  1      1     1  27000.0  90.0  990.0
  2      2     2  19000.0  17.0  750.0
  3      3     3  70000.0  60.0  900.0
  4      4     4   6000.0   7.0  810.0,
  24:    index  date        a     b      c
  0      0     0  12000.0  50.0   60.0
  1      1     1  27000.0  90.0  990.0
  2      2     2  19000.0  17.0  750.0
  3      3     3  70000.0  60.0  900.0
  4      4     4   6000.0   7.0  810.0},
 '_dh': [PosixPath('/Users/adnanaltimeemy')],
 'In': ['',
  'import pandas as pd\nimport numpy as np\n\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom sklearn.impute import SimpleImputer\n\nfrom sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier\nfrom sklearn.tree import DecisionTreeClassifier\n\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix',
  'df = pd.read_csv("Merge2.csv")\n\n# View dataset\nprint(df.head())\nprint(df.info())',
  '# Check missing values\nprint(df.isnull().sum())\n\n# Separate numeric and categorical columns\nnumeric_cols = df.select_dtypes(include=np.number).columns\ncategorical_cols = df.select_dtypes(include=\'object\').columns\n\n# Fill missing values\nnum_imputer = SimpleImputer(strategy="mean")\ndf[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])\n\ncat_imputer = SimpleImputer(strategy="most_frequent")\ndf[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])',
  "categorical_cols = df.select_dtypes(include='object').columns",
  "df.select_dtypes(include='object')",
  "df.select_dtypes(include='object')",
  "df.select_dtypes(include=['object', 'string', 'category'])",
  'label_encoders = {}\n\nfor col in categorical_cols:\n    le = LabelEncoder()\n    df[col] = le.fit_transform(df[col])\n    label_encoders[col] = le',
  'X = df.drop("target", axis=1)\ny = df["target"]',
  'df.head()\ndf.index',
  'df = df.reset_index()',
  'X_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)',
  'df.head()',
  'rf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\nrf_model.fit(X_train, y_train)\n\nrf_pred = rf_model.predict(X_test)',
  'print(globals().keys())',
  'et_model = ExtraTreesClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\net_model.fit(X_train, y_train)\n\net_pred = et_model.predict(X_test)',
  'import pandas as pd\n\nimportances = pd.Series(et_model.feature_importances_, index=X_train.columns)\nprint(importances.sort_values(ascending=False).head(10))',
  'from sklearn.ensemble import ExtraTreesClassifier\n\net_model = ExtraTreesClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\net_model.fit(X_train, y_train)   # MUST run first\n\nimport pandas as pd\n\nimportances = pd.Series(et_model.feature_importances_, index=X_train.columns)\nprint(importances.sort_values(ascending=False).head(10))',
  'print(et_model)\nprint(len(et_model.estimators_))',
  'X_train.isnull().sum().sum()',
  'print(type(X_train))\nprint(X_train.shape)',
  'import pandas as pd\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import ExtraTreesClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\n# ----------------------------\n# 1. Define features & target\n# ----------------------------\nX = df.drop("target", axis=1)   # change "target" to your label column\ny = df["target"]\n\n# ----------------------------\n# 2. Train/test split\n# ----------------------------\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y,\n    test_size=0.2,\n    random_state=42\n)\n\n# ----------------------------\n# 3. Train model\n# ----------------------------\net_model = ExtraTreesClassifier(\n    n_estimators=100,\n    random_state=42,\n    n_jobs=-1\n)\n\net_model.fit(X_train, y_train)\n\n# ----------------------------\n# 4. Predictions\n# ----------------------------\net_pred = et_model.predict(X_test)\n\n# ----------------------------\n# 5. Evaluation\n# ----------------------------\nprint("Accuracy:", accuracy_score(y_test, et_pred))\nprint("\\nClassification Report:\\n", classification_report(y_test, et_pred))\n\n# ----------------------------\n# 6. Feature Importance\n# ----------------------------\nimportances = pd.Series(et_model.feature_importances_, index=X.columns)\nprint("\\nTop 10 Features:\\n")\nprint(importances.sort_values(ascending=False).head(10))',
  'print(df.columns)',
  'df.head()',
  'for col in df.columns:\n    print(col)',
  'dt_model = DecisionTreeClassifier(random_state=42)\ndt_model.fit(X_train, y_train)\n\ndt_pred = dt_model.predict(X_test)',
  'print(X.shape, y.shape)',
  'from sklearn.metrics import accuracy_score\n\naccuracy = accuracy_score(y_test, dt_pred)\nprint("Accuracy:", accuracy)',
  'from sklearn.metrics import accuracy_score\n\naccuracy = accuracy_score(y_test, dt_pred)\nprint("Accuracy:", accuracy)',
  'print(X.shape)\nprint(y.shape)',
  'from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.metrics import accuracy_score\n\n# Load data\ndata = load_iris()\nX = data.data\ny = data.target\n\n# Split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Train model\ndt_model = DecisionTreeClassifier(random_state=42)\ndt_model.fit(X_train, y_train)\n\n# Predict\ndt_pred = dt_model.predict(X_test)\n\n# Evaluate\naccuracy = accuracy_score(y_test, dt_pred)\nprint("Accuracy:", accuracy)',
  'print("Extra Trees Accuracy:", accuracy_score(y_test, et_pred))\nprint(classification_report(y_test, et_pred))',
  'print(dir())',
  'predict(',
  'print("Random Forest Confusion Matrix")\nprint(confusion_matrix(y_test, rf_pred))',
  'print(dir())',
  'locals()'],
 'Out': {5:           date
  0   2022-03-01
  1   2022-03-02
  2   2022-03-03
  3   2022-03-04
  4   2022-03-05
  5   2022-03-06
  6   2022-03-07
  7   2022-03-08
  8   2022-03-09
  9   2022-03-10
  10  2022-03-11
  11  2022-03-12
  12  2022-03-13
  13  2022-03-14
  14  2022-03-15
  15  2022-03-16
  16  2022-03-17
  17  2022-03-18
  18  2022-03-19
  19  2022-03-20
  20  2022-03-21
  21  2022-03-22
  22  2022-03-23
  23  2022-03-24
  24  2022-03-25
  25  2022-03-26
  26  2022-03-27
  27  2022-03-28
  28  2022-03-29
  29  2022-03-30
  30  2022-03-31,
  6:           date
  0   2022-03-01
  1   2022-03-02
  2   2022-03-03
  3   2022-03-04
  4   2022-03-05
  5   2022-03-06
  6   2022-03-07
  7   2022-03-08
  8   2022-03-09
  9   2022-03-10
  10  2022-03-11
  11  2022-03-12
  12  2022-03-13
  13  2022-03-14
  14  2022-03-15
  15  2022-03-16
  16  2022-03-17
  17  2022-03-18
  18  2022-03-19
  19  2022-03-20
  20  2022-03-21
  21  2022-03-22
  22  2022-03-23
  23  2022-03-24
  24  2022-03-25
  25  2022-03-26
  26  2022-03-27
  27  2022-03-28
  28  2022-03-29
  29  2022-03-30
  30  2022-03-31,
  7:           date
  0   2022-03-01
  1   2022-03-02
  2   2022-03-03
  3   2022-03-04
  4   2022-03-05
  5   2022-03-06
  6   2022-03-07
  7   2022-03-08
  8   2022-03-09
  9   2022-03-10
  10  2022-03-11
  11  2022-03-12
  12  2022-03-13
  13  2022-03-14
  14  2022-03-15
  15  2022-03-16
  16  2022-03-17
  17  2022-03-18
  18  2022-03-19
  19  2022-03-20
  20  2022-03-21
  21  2022-03-22
  22  2022-03-23
  23  2022-03-24
  24  2022-03-25
  25  2022-03-26
  26  2022-03-27
  27  2022-03-28
  28  2022-03-29
  29  2022-03-30
  30  2022-03-31,
  10: RangeIndex(start=0, stop=31, step=1),
  13:    index  date        a     b      c
  0      0     0  12000.0  50.0   60.0
  1      1     1  27000.0  90.0  990.0
  2      2     2  19000.0  17.0  750.0
  3      3     3  70000.0  60.0  900.0
  4      4     4   6000.0   7.0  810.0,
  24:    index  date        a     b      c
  0      0     0  12000.0  50.0   60.0
  1      1     1  27000.0  90.0  990.0
  2      2     2  19000.0  17.0  750.0
  3      3     3  70000.0  60.0  900.0
  4      4     4   6000.0   7.0  810.0},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10464acc0>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x104648260>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x104648260>,
 'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
 '_':    index  date        a     b      c
 0      0     0  12000.0  50.0   60.0
 1      1     1  27000.0  90.0  990.0
 2      2     2  19000.0  17.0  750.0
 3      3     3  70000.0  60.0  900.0
 4      4     4   6000.0   7.0  810.0,
 '__':    index  date        a     b      c
 0      0     0  12000.0  50.0   60.0
 1      1     1  27000.0  90.0  990.0
 2      2     2  19000.0  17.0  750.0
 3      3     3  70000.0  60.0  900.0
 4      4     4   6000.0   7.0  810.0,
 '___': RangeIndex(start=0, stop=31, step=1),
 '__session__': '/Users/adnanaltimeemy/Untitled22.ipynb',
 '_i': 'print(dir())',
 '_ii': 'print("Random Forest Confusion Matrix")\nprint(confusion_matrix(y_test, rf_pred))',
 '_iii': 'predict(',
 '_i1': 'import pandas as pd\nimport numpy as np\n\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\nfrom sklearn.impute import SimpleImputer\n\nfrom sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier\nfrom sklearn.tree import DecisionTreeClassifier\n\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix',
 'pd': <module 'pandas' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/pandas/__init__.py'>,
 'np': <module 'numpy' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/numpy/__init__.py'>,
 'train_test_split': <function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>,
 'LabelEncoder': sklearn.preprocessing._label.LabelEncoder,
 'SimpleImputer': sklearn.impute._base.SimpleImputer,
 'RandomForestClassifier': sklearn.ensemble._forest.RandomForestClassifier,
 'ExtraTreesClassifier': sklearn.ensemble._forest.ExtraTreesClassifier,
 'DecisionTreeClassifier': sklearn.tree._classes.DecisionTreeClassifier,
 'accuracy_score': <function sklearn.metrics._classification.accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)>,
 'classification_report': <function sklearn.metrics._classification.classification_report(y_true, y_pred, *, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn')>,
 'confusion_matrix': <function sklearn.metrics._classification.confusion_matrix(y_true, y_pred, *, labels=None, sample_weight=None, normalize=None)>,
 '_i2': 'df = pd.read_csv("Merge2.csv")\n\n# View dataset\nprint(df.head())\nprint(df.info())',
 'df':     index  date        a     b      c
 0       0     0  12000.0  50.0   60.0
 1       1     1  27000.0  90.0  990.0
 2       2     2  19000.0  17.0  750.0
 3       3     3  70000.0  60.0  900.0
 4       4     4   6000.0   7.0  810.0
 5       5     5  10000.0  98.0  730.0
 6       6     6  41000.0  21.0  710.0
 7       7     7  80000.0  76.0  200.0
 8       8     8  78000.0  46.0  200.0
 9       9     9  74000.0  67.0   50.0
 10     10    10  13000.0  20.0   70.0
 11     11    11   9000.0   8.0  100.0
 12     12    12  44000.0  56.0  350.0
 13     13    13  44000.0  34.0  370.0
 14     14    14  39000.0  29.0  420.0
 15     15    15  21000.0  37.0  920.0
 16     16    16  59000.0   1.0  480.0
 17     17    17  19000.0  17.0  850.0
 18     18    18  74000.0  34.0  730.0
 19     19    19   6000.0  89.0  100.0
 20     20    20  67000.0  37.0   70.0
 21     21    21  74000.0  12.0   70.0
 22     22    22  31000.0  43.0  340.0
 23     23    23  12000.0  13.0  850.0
 24     24    24  94000.0  81.0  930.0
 25     25    25  85000.0   7.0  650.0
 26     26    26  17000.0  89.0  230.0
 27     27    27  97000.0  69.0  790.0
 28     28    28  47000.0  54.0  970.0
 29     29    29  72000.0  27.0  600.0
 30     30    30  80000.0  17.0  370.0,
 '_i3': '# Check missing values\nprint(df.isnull().sum())\n\n# Separate numeric and categorical columns\nnumeric_cols = df.select_dtypes(include=np.number).columns\ncategorical_cols = df.select_dtypes(include=\'object\').columns\n\n# Fill missing values\nnum_imputer = SimpleImputer(strategy="mean")\ndf[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])\n\ncat_imputer = SimpleImputer(strategy="most_frequent")\ndf[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])',

In [40]:
print(rf_model)

RandomForestClassifier(random_state=42)