In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv("citywages.csv")
df.head()

                                   Metro  POP_1980  ...   state_display  highlight
0  new york-newark-jersey city, ny-nj-pa  14734200  ...             NaN        1.0
1     los angeles-long beach-anaheim, ca   9428000  ...             NaN        NaN
2     chicago-naperville-elgin, il-in-wi   7744700  ...  Ill.-Ind.Wisc.        1.0
3        dallas-fort worth-arlington, tx   2968500  ...            Tex.        NaN
4   houston-the woodlands-sugar land, tx   2919400  ...            Tex.        1.0

[5 rows x 10 columns]

In [4]:
cat_cols = df.select_dtypes(include=['object', 'string', 'category']).columns

label_encoders = {}

for column in cat_cols:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column].astype(str))
    label_encoders[column] = le

In [6]:
print(df.head())
print(df.columns.tolist())

   Metro  POP_1980  LPOP_1980  ...  nyt_display  state_display  highlight
0    116  14734200        7.2  ...          114             61        1.0
1     95   9428000        7.0  ...           93             61        NaN
2     35   7744700        6.9  ...           35             15        1.0
3     45   2968500        6.5  ...           44             53        NaN
4     73   2919400        6.5  ...           72             53        1.0

[5 rows x 10 columns]
['Metro', 'POP_1980', 'LPOP_1980', 'R90_10_1980', 'POP_2015', 'LPOP_2015', 'R90_10_2015', 'nyt_display', 'state_display', 'highlight']

In [9]:
df.head()
df.columns

Index(['Metro', 'POP_1980', 'LPOP_1980', 'R90_10_1980', 'POP_2015',
       'LPOP_2015', 'R90_10_2015', 'nyt_display', 'state_display',
       'highlight'],
      dtype='str')

In [12]:
df.columns

Index(['Metro', 'POP_1980', 'LPOP_1980', 'R90_10_1980', 'POP_2015',
       'LPOP_2015', 'R90_10_2015', 'nyt_display', 'state_display',
       'highlight'],
      dtype='str')

In [13]:
df.head()

   Metro  POP_1980  LPOP_1980  ...  nyt_display  state_display  highlight
0    116  14734200        7.2  ...          114             61        1.0
1     95   9428000        7.0  ...           93             61        NaN
2     35   7744700        6.9  ...           35             15        1.0
3     45   2968500        6.5  ...           44             53        NaN
4     73   2919400        6.5  ...           72             53        1.0

[5 rows x 10 columns]

In [18]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'RandomForestRegressor', 'ExtraTreesRegressor', 'mean_squared_error', 'r2_score', '_i2', 'df', '_2', '_i3', 'label_encoders', 'column', 'le', '_i4', 'cat_cols', '_i5', '_i6', '_i7', '_i8', '_i9', '_9', '_i10', 'rf_model', '_i11', '_i12', '_12', '_i13', '_13', '_i14', 'et_model', '_i15', '_i16', '_i17', '_i18'])

In [22]:
def train_models(X, y):
    rf_model.fit(X, y)
    et_model.fit(X, y)
    return rf_model, et_model

In [23]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'RandomForestRegressor', 'ExtraTreesRegressor', 'mean_squared_error', 'r2_score', '_i2', 'df', '_2', '_i3', 'label_encoders', 'column', 'le', '_i4', 'cat_cols', '_i5', '_i6', '_i7', '_i8', '_i9', '_9', '_i10', 'rf_model', '_i11', '_i12', '_12', '_i13', '_13', '_i14', 'et_model', '_i15', '_i16', '_i17', '_i18', '_i19', 'plt', '_i20', '_i21', '_i22', 'train_models', '_i23'])