In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("shops.csv")

# Show first rows
df.head()

            Shop                         Item  Cost
0  Papa B's Pawn             Electronic Parts  50.0
1  Papa B's Pawn           Chemical Component   NaN
2  Papa B's Pawn  Unstable Chemical Component   NaN

In [3]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Shop    3 non-null      str
 1   Item    3 non-null      str
 2   Cost    1 non-null      float64
dtypes: float64(1), str(2)
memory usage: 304.0 bytes

Shop    0
Item    0
Cost    2
dtype: int64

In [5]:
df.columns = df.columns.str.lower()

In [6]:
if text_column in df.columns:
    df[text_column] = df[text_column].fillna("")
    texts = df[text_column]
else:
    print(f"Column '{text_column}' not found. Available columns: {df.columns}")

Column 'description' not found. Available columns: Index(['shop', 'item', 'cost'], dtype='str')

In [9]:
print(df.columns)

Index(['shop', 'item', 'cost'], dtype='str')

In [11]:
df.head()

            shop                         item  cost
0  Papa B's Pawn             Electronic Parts  50.0
1  Papa B's Pawn           Chemical Component   NaN
2  Papa B's Pawn  Unstable Chemical Component   NaN

In [13]:
print(df.columns)
print(df.head())

Index(['shop', 'item', 'cost'], dtype='str')
            shop                         item  cost
0  Papa B's Pawn             Electronic Parts  50.0
1  Papa B's Pawn           Chemical Component   NaN
2  Papa B's Pawn  Unstable Chemical Component   NaN

In [18]:
print("Columns:", df.columns)

if "cluster" not in df.columns:
    print("Cluster column missing!")

Columns: Index(['shop', 'item', 'cost'], dtype='str')
Cluster column missing!