In [1]:
# If needed (run once)
# !pip install pandas numpy scikit-learn nltk matplotlib seaborn

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

import nltk
import re
import string

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("undefeated.csv")

# View data
df.head()

          name                             url        date  wins
0  Juro Fukuda  http://boxrec.com/boxer/195508  1941-01-24     1
1  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-18     2
2  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-26     3
3  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-06     4
4  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-25     5

In [3]:
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 2125 entries, 0 to 2124
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2125 non-null   str
 1   url     2125 non-null   str
 2   date    2125 non-null   str
 3   wins    2125 non-null   int64
dtypes: int64(1), str(3)
memory usage: 176.3 KB

Index(['name', 'url', 'date', 'wins'], dtype='str')

In [5]:

df.head()

          name                             url        date  wins
0  Juro Fukuda  http://boxrec.com/boxer/195508  1941-01-24     1
1  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-18     2
2  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-26     3
3  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-06     4
4  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-25     5

In [7]:
df.head()

          name                             url        date  wins
0  Juro Fukuda  http://boxrec.com/boxer/195508  1941-01-24     1
1  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-18     2
2  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-26     3
3  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-06     4
4  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-25     5

In [8]:
for col in df.columns:
    print(col)

name
url
date
wins

In [10]:
print(df.head())
print(df.columns.tolist())

          name                             url        date  wins
0  Juro Fukuda  http://boxrec.com/boxer/195508  1941-01-24     1
1  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-18     2
2  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-26     3
3  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-06     4
4  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-25     5
['name', 'url', 'date', 'wins']

In [12]:
df.head()

          name                             url        date  wins
0  Juro Fukuda  http://boxrec.com/boxer/195508  1941-01-24     1
1  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-18     2
2  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-26     3
3  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-06     4
4  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-25     5

In [14]:
from sklearn.cluster import KMeans

# choose numeric features (common approach)
X = df.select_dtypes(include=["number"])

k = 4  # based on elbow method

kmeans = KMeans(n_clusters=k, random_state=42)
df["cluster"] = kmeans.fit_predict(X)

df.head()

          name                             url        date  wins  cluster
0  Juro Fukuda  http://boxrec.com/boxer/195508  1941-01-24     1        0
1  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-18     2        0
2  Juro Fukuda  http://boxrec.com/boxer/195508  1941-02-26     3        0
3  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-06     4        0
4  Juro Fukuda  http://boxrec.com/boxer/195508  1941-04-25     5        0

In [15]:
df["cluster"].value_counts()

cluster
0    734
2    724
1    507
3    160
Name: count, dtype: int64

In [17]:
print(hasattr(vectorizer, "vocabulary_"))

False

In [19]:
if text_col not in df.columns:
    print("Available columns:", df.columns)

Available columns: Index(['name', 'url', 'date', 'wins', 'cluster'], dtype='str')

In [20]:
df.to_csv("undefeated_clustered.csv", index=False)